services:
  - name: opengovdatahub-backend
    type: web
    source:
      git:
        url: https://github.com/Mxgrig/opengovdatahub-backend
        branch: main
    build:
      type: buildpack
    ports:
      - port: 8000
        protocol: http
    regions:
      - fra
    instance_types:
      - nano
    env:
      - name: NODE_ENV
        value: production
      - name: PORT
        value: "8000"
      - name: JWT_SECRET
        value: opengovdatahub-super-secure-jwt-2024-production
      - name: FRONTEND_URL
        value: https://opengovdatahub.com
    health_checks:
      - path: /api/health
        port: 8000
        protocol: http